# Generated by Django 3.1.4 on 2020-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Side_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='facebook_link')),
                ('linkedin_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='linkedin_link')),
                ('github_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='github_link')),
                ('researchgate_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='researchgate_link')),
                ('google_sch_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='google_sch_link')),
                ('my_website_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='my_website_link')),
                ('side_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_status', models.CharField(blank=True, max_length=100, null=True)),
                ('long_intro', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
