# Generated by Django 3.1.4 on 2020-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_profile',
            name='main_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
