# Generated by Django 3.1.4 on 2020-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0002_side_profile_main_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='what_i_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wid_Short_intro', models.TextField(blank=True, max_length=800, null=True)),
                ('fab_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('wid_title', models.CharField(blank=True, max_length=100, null=True)),
                ('wid_details', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
