# Generated by Django 3.1.4 on 2020-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0003_what_i_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_i_do',
            name='Wid_Short_intro',
        ),
        migrations.AddField(
            model_name='side_profile',
            name='Wid_Short_intro',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
