# Generated by Django 3.1.4 on 2020-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0004_auto_20201225_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='testiomonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_details', models.TextField(blank=True, max_length=800, null=True)),
                ('test_name', models.CharField(blank=True, max_length=100, null=True)),
                ('test_job_status', models.CharField(blank=True, max_length=200, null=True)),
                ('test_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
