# Generated by Django 3.1.4 on 2021-01-07 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('project_discription', models.TextField(blank=True, max_length=600, null=True)),
                ('project_main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('technology_used', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('company_size', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('project_github_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='project_github_link')),
                ('client_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Client_link')),
                ('content', models.TextField(blank=True)),
                ('project_requirement', models.TextField(blank=True)),
                ('project_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_overview', models.TextField(blank=True)),
                ('project_Challenge', models.TextField(blank=True)),
                ('approach_Solution', models.TextField(blank=True)),
                ('client_Testimonial', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
